services:
  - type: web
    name: fastapi-app
    runtime: python
    pythonVersion: 3.11
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn ai:app --host 0.0.0.0 --port 10000
